### ISSUE TITLE
Prowlarr config template doesn't work after 1.14.3.4333

### ISSUE THREAD

**Issue by Toastyice** [onedr0p/containers#1010]
Upgrading from 1.14.3.4333 to 1.16.1.4420 the entrypoint script does no longer create the prowlarr config from env vars
I don't have any persistent storage mounted to the container.

Example version: ghcr.io/onedr0p/prowlarr-develop:1.14.3.4333
[Info] Bootstrap: Starting Prowlarr - /app/bin/Prowlarr - Version 1.14.3.4333 
2024-04-20T10:35:43.705384522+02:00 [Info] AppFolderInfo: Data directory is being overridden to [/config] 
2024-04-20T10:35:43.737502198+02:00 [Debug] Bootstrap: Console selected 
2024-04-20T10:35:43.742116511+02:00 [Info] AppFolderInfo: Data directory is being overridden to [/config] 
2024-04-20T10:35:44.157850004+02:00 [Info] AppFolderInfo: Data directory is being overridden to [/config] 
2024-04-20T10:35:44.277479707+02:00 [Info] MigrationController: *** Migrating Database=prowlarr;Host=holon-pgbouncer.postgres.svc;Username=prowlarr;Password=mypassword;Port=5432;Enlist=False *** 

Example version: ghcr.io/onedr0p/prowlarr-develop:1.16.1.4420
/entrypoint.sh: line 23: /config/config.xml: No such file or directory
[Info] Bootstrap: Starting Prowlarr - /app/bin/Prowlarr - Version 1.16.1.4420 
2024-04-20T10:22:44.191697868+02:00 [Info] AppFolderInfo: Data directory is being overridden to [/config] 
2024-04-20T10:22:44.198994787+02:00 [Debug] Bootstrap: Console selected 
2024-04-20T10:22:44.200191209+02:00 [Info] AppFolderInfo: Data directory is being overridden to [/config] 
2024-04-20T10:22:44.552854025+02:00 [Info] AppFolderInfo: Data directory is being overridden to [/config] 
2024-04-20T10:22:44.766077679+02:00 [Info] MigrationController: *** Migrating data source=/config/prowlarr.db;cache size=-20000;datetimekind=Utc;journal

**Comment by onedr0p** [comment]
I'm curious if this is related to permissions as things changed recently, look at the release notes and the README.

**Comment by kusold** [comment]
I think there is something to this. Updating to the image below broke my config. Post update, `/config/config.xml` no longer contains any references to Postgres.

This is the first release that I was able to reproduce this with:
```diff
- ghcr.io/onedr0p/prowlarr:1.15.0@sha256:73e30e7c9eddd7aca3de4208e702d6293862bb5c49d7a8547cc1b9e3c35dcb86
+ ghcr.io/onedr0p/prowlarr:1.15.0@sha256:cf646c64fdb90f3acddb5e2ec6ffad064392ad1aaf9da7875b8a7a962263f5fc
```


I am properly setting the env vars:
```
a9a397ddab72:/app# env | grep PROWLARR__
PROWLARR__BRANCH=master
PROWLARR__INSTANCE_NAME=Prowlarr
PROWLARR__ANALYTICS_ENABLED=False
PROWLARR__API_KEY=<REDACTED>
PROWLARR__POSTGRES_PASSWORD=<REDACTED>
PROWLARR__POSTGRES_LOG_DB=prowlarr-log
PROWLARR__PORT=9696
PROWLARR__POSTGRES_HOST=<REDACTED>
PROWLARR__POSTGRES_USER=prowlarr
PROWLARR__POSTGRES_MAIN_DB=prowlarr-main
```

Here is the config post update:
```
a9a397ddab72:/app# cat /config/config.xml
<Config>
  <BindAddress>*</BindAddress>
  <Port>9696</Port>
  <SslPort>6969</SslPort>
  <EnableSsl>False</EnableSsl>
  <LaunchBrowser>True</LaunchBrowser>
  <ApiKey>9f58b9cbaf3f4c9e89576ff2c4c9c57e</ApiKey>
  <AuthenticationMethod>None</AuthenticationMethod>
  <AuthenticationRequired>Enabled</AuthenticationRequired>
  <Branch>master</Branch>
  <LogLevel>info</LogLevel>
```

I've also attempted to update to `ghcr.io/onedr0p/prowlarr:1.16.2@sha256:7e54724e4119386b9d992350c9fd269fd1b94ad9d51484d7b66b94a7754fbde`, but received the same results.

**Comment by onedr0p** [comment]
I'm a bit confused on why this is happening since there has been no significant updates to those scripts. The only things that have changed recently is the move to upstream alpine base and the user change. 

With that said I'm still using this image and updated from 1.14 to 1.15 to 1.16 without issue.

**Comment by kusold** [comment]
Using the 1.16 image, when it starts `/config/config.xml` is missing all of the Postgres related config. However, when I exec into the container and manually run `/entrypoint.sh` everything populates correctly in the config.xml. Also, I use a few of your other containers, and Prowlarr is the only one having the issue. 🤔 

According to my git history, I started using the known-good version (`73e30e7`) on April 2nd. On April 18th, I attempted to use the 1.15 `cf646c6` version. So the change that breaks me should be hiding [in one of these commits](https://github.com/onedr0p/containers/commits/main/apps/prowlarr/Dockerfile?since=2024-04-02&until=2024-04-18). 

The UMASK commit didn't work on my system ( I still had 0022), but I set it to `0000` via the `--umask` [flag](https://docs.podman.io/en/latest/markdown/podman-run.1.html#umask-umask) and the problem persisted.

I'm running Prowlarr as root, so it shouldn't be permission issues (famous last words):
```
/app # ps aux
PID   USER     TIME  COMMAND
    1 root      0:00 /usr/bin/catatonit -- /entrypoint.sh
    2 root      0:03 /app/bin/Prowlarr --nobrowser --data=/config
   17 root      0:00 /bin/sh
   28 root      0:00 ps aux
```

I'd appreciate any debugging ideas you have. I've run out for the moment.

---

This is my NixOS config in case you spot something that differs from yours. Besides for my choice in OS, I think everything else is pretty standard.

* No volume mounts (including not persisting /config)
* Systemd destroys the container as part of my `ExecStartPre`, so it's a clean container every time it starts.
* Uses Podman
* Not specifying a user. Podman launches the container with root permissions.
* Load envs via file
* x86_64 arch

```
  virtualisation.oci-containers.containers."prowlarr" = {
    image = "ghcr.io/onedr0p/prowlarr:1.15.0@sha256:73e30e7c9eddd7aca3de4208e702d6293862bb5c49d7a8547cc1b9e3c35dcb86"; # Last good version
    autoStart = true;
    environmentFiles = [
      config.age.secrets.prowlarr-env.path
    ];
    dependsOn = [ "gluetun" ];
    extraOptions = [
      "--network=container:gluetun"
    ];
    volumes = [ ];
    environment = { };
  };
```


@Toastyice Please let me know if you make progress on this. Maybe we can figure it out together.

**Comment by onedr0p** [comment]
I will try to reproduce this with a simple docker-compose file when I have time unless someone can get to it first.

**Comment by kusold** [comment]
Thanks for reopening this.

The following reproduces for me, using Docker Desktop for Mac.

To test:
1. Make sure the proper image is uncommented
2. `docker compose up -d`
3. `docker compose exec -it prowlarr /bin/bash -c "cat /config/config.xml"`
5. `docker compose down`, swap the image, and 🔁  

prowlarr-init.sh
```shell
#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE DATABASE "prowlarr-logs";
	GRANT ALL PRIVILEGES ON DATABASE "prowlarr-logs" TO prowlarr;
EOSQL
```

docker-compose.yaml
```yaml
version: '3'
services:
  prowlarr:
    # Good Image
    # image: ghcr.io/onedr0p/prowlarr:1.15.0@sha256:73e30e7c9eddd7aca3de4208e702d6293862bb5c49d7a8547cc1b9e3c35dcb86
    # Bad Image
    image: ghcr.io/onedr0p/prowlarr:rolling@sha256:7e54724e4119386b9d992350c9fd269fd1b94ad9d51484d7b66b94a7754fbde6
    ports: []
    volumes: []
    environment:
      - PROWLARR__POSTGRES_HOST=db
      - PROWLARR__POSTGRES_MAIN_DB=prowlarr-main
      - PROWLARR__POSTGRES_LOG_DB=prowlarr-logs
      - PROWLARR__POSTGRES_PASSWORD=prowlarr-pass
      - PROWLARR__POSTGRES_USER=prowlarr
      - PROWLARR__API_KEY=1234567890
    depends_on:
      - db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9696/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  db:
    image: postgres:16
    ports: []
    volumes:
      - ./prowlarr-init.sh:/docker-entrypoint-initdb.d/prowlarr-init.sh
    environment:
      - POSTGRES_USER=prowlarr
      - POSTGRES_DB=prowlarr-main
      - POSTGRES_PASSWORD=prowlarr-pass
```
