### ISSUE TITLE
Refactor goss tests

### ISSUE THREAD

**Issue by onedr0p** [onedr0p/containers#1114]
There is a limitation on goss when testing a container and having an `ENTRYPOINT` like this:

```Dockerfile
ENTRYPOINT ["/usr/bin/catatonit", "--", "/entrypoint.sh"]
```

Goss will attempt to run the container and it will likely fail because the `entrypoint.sh` will never exit 0

I suggest to make the tests a simple toggle to enable / disable, e.g.

```yaml
app: postgres-init
semver: true
test: false
channels:
  - name: stable
    platforms: ["linux/amd64", "linux/arm64"]
    stable: true
```
